### PR TITLE
Dockerfile for temporal-ydb added

### PR DESCRIPTION
**Pull request by karelinoleg**

### CODE REVIEW

**Comment by karelinoleg** [comment]
I hereby agree to the terms of the CLA available at https://yandex.ru/legal/cla/?lang=en

**Comment by karelinoleg** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

**Comment by karelinoleg** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Comment by aromanovich** [comment]
Shipped!

**Comment by karelinoleg** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

**Pull request closed without merging**
